[workspace]
members = ["player",
           "game_sdk",
           "referee",
           "xml_client",
           "demo",
           "referee_client"]

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
debug= true
[profile.test]
opt-level = 3