[package]
name = "referee"
version = "0.1.0"
authors = ["imkgerC <imrund08@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
game_sdk = { path = "../game_sdk"}
rand = "0.7.3"